name: open/edit/sync Pull Request
on:
  pull_request:
    types: ["opened", "edited", "synchronize"]
    branches: ["dev"]

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
      - run: |
          ${{ steps.setup-chrome.outputs.chrome-path }} --version
      
      - name: Cache Lighthouse
        id: cache-lhci
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/lhci
            node_modules
          key: lhci-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - if: ${{ steps.cache-lhci.outputs.cache-hit != 'true' }}
        name: Lighthouse install
        run: npm install -g @lhci/cli

      - name: run Lighthouse CI
        run: lhci autorun
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_SHOP_PASSWORD: ${{ secrets.SHOP_PASSWORD }}
          HOST: https://${{ secrets.SHOP_STORE }}
          THEME_ID_PREVIEW: ${{ secrets.THEME_ID_PREVIEW }}
          COLLECTION_URL: ${{ secrets.COLLECTION_URL }}
          PRODUCT_URL: ${{ secrets.PRODUCT_URL }}